Temporary Puppet version

diff --git a/ops/cloudformation/cfn_asg.yml b/ops/cloudformation/cfn_asg.yml
--- a/ops/cloudformation/cfn_asg.yml
+++ b/ops/cloudformation/cfn_asg.yml
@@ -24,12 +24,11 @@ Parameters:
     Type: String
     Description: Type of EC2 instance.
     Default: t2.micro
-    AllowedValues: [ t2.micro, t2.small, t2.medium ]
     ConstraintDescription: Must be a valid EC2 instance type.
   WebASGCapacity:
     Description: The number of ec2 instances will be runned into ASG
     Type: String
-    Default: "2"
+    Default: "1"
     ConstraintDescription: Must be positive integer or zero
   S3Path:
     Type: String
@@ -65,6 +64,9 @@ Resources:
           FromPort: '8080'
           ToPort: '8080'
           CidrIp: 0.0.0.0/0
+      Tags:
+        - Key: "Name"
+          Value: "webAppSG"
 
   LaunchConfig:
     Type: "AWS::AutoScaling::LaunchConfiguration"
@@ -105,31 +107,37 @@ Resources:
           }
           # retryCommand 5 10 'aws s3 cp "s3://${S3Path}/scripts/web/web_application-${ver}.tar" .'
           retryCommand 5 10 "yum -y update"
-          retryCommand 5 10 "yum -y install tomcat"
-          retryCommand 5 10 "yum -y install tomcat-webapps tomcat-admin-webapps tomcat-docs-webapp tomcat-javadoc"
-          retryCommand 5 10 "yum -y install unzip"
-          mv /var/lib/tomcat/webapps/ROOT/ /var/lib/tomcat/webapps/default-ROOT
-          mkdir webapp/
-          cd webapp/
-          wget https://devopsa3-simple-java-app.s3.amazonaws.com/java-tomcat-v3.zip
-          retryCommand 5 10 "unzip java-tomcat-v3.zip"
-          cd ../
-          mv webapp/ /var/lib/tomcat/webapps/ROOT
-          systemctl start tomcat
-          systemctl enable tomcat
-          sleep 10s
-          curl -sS http://localhost:8080/index.jsp
-          cfn-signal -e $? --stack ${AWS::StackName} --resource webAppASG --region ${AWS::Region}
+          # retryCommand 5 10 "yum -y install tomcat"
+          # retryCommand 5 10 "yum -y install tomcat-webapps tomcat-admin-webapps tomcat-docs-webapp tomcat-javadoc"
+          # retryCommand 5 10 "yum -y install unzip"
+          # mv /var/lib/tomcat/webapps/ROOT/ /var/lib/tomcat/webapps/default-ROOT
+          # mkdir webapp/
+          # cd webapp/
+          # wget https://devopsa3-simple-java-app.s3.amazonaws.com/java-tomcat-v3.zip
+          # retryCommand 5 10 "unzip java-tomcat-v3.zip"
+          # cd ../
+          # mv webapp/ /var/lib/tomcat/webapps/ROOT
+          # systemctl start tomcat
+          # systemctl enable tomcat
+          # sleep 10s
+          # curl -sS http://localhost:8080/index.jsp
+          # cfn-signal -e $? --stack ${AWS::StackName} --resource webAppASG --region ${AWS::Region}
           echo "SECTION #2 - INSTALL PUPPET AGENT"
-          rpm -Uvh https://yum.puppet.com/puppet5-release-el-7.noarch.rpm
+          retryCommand 5 10 'rpm -Uvh https://yum.puppet.com/puppet5-release-el-7.noarch.rpm'
           retryCommand 5 10 "yum -y update"
           retryCommand 5 10 'yum install -y puppet-agent'
           export PATH=$PATH:/opt/aws/bin/:/opt/puppetlabs/bin/:/opt/puppetlabs/puppet/bin
-          retryCommand 5 10  'aws s3 cp "s3://${S3Path}/scripts/web/puppet-${pupver}.tar" .'
-          tar -C /etc/puppetlabs/ -xvf puppet-${pupver}.tar
+          # retryCommand 5 10  'aws s3 cp "s3://${S3Path}/scripts/jenkins/puppet-${pupver}.tar" .'
+          wget https://devopsa3-simple-java-app.s3.amazonaws.com/puppet-0.0.1.tar
+          retryCommand 5 10 'tar -C /etc/puppetlabs/ -xvf puppet-${pupver}.tar'
+          systemctl start puppet
+          systemctl enable puppet
+          sleep 30
           retryPuppetCommand 5 10 'puppet apply --test /etc/puppetlabs/code/environments/production/manifests/site.pp' && echo "Finished puppet"
           sleep 30
           systemctl status puppet
+          curl -sS http://localhost:8080/index.jsp
+          # cfn-signal -e $? --stack ${AWS::StackName} --resource webAppASG --region ${AWS::Region}
         - ver: !Ref WebAppVersion
           pupver: !Ref PuppetScriptVersion
       AssociatePublicIpAddress: "false"
@@ -155,9 +163,9 @@ Resources:
         - Fn::ImportValue: !Sub "${VPCStackName}-PrivateSubnet1"
       Tags:
         - Key: "Name"
-          Value: "webASG"
+          Value: "webserver"
           PropagateAtLaunch: true
-    CreationPolicy:
-      ResourceSignal:
-        Count: !Ref WebASGCapacity
-        Timeout: "PT20M"
+#    CreationPolicy:
+#      ResourceSignal:
+#        Count: !Ref WebASGCapacity
+#        Timeout: "PT20M"
